/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author neel
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
   private User newUser;

    public ViewPanel(User newUser) {
        initComponents();
        this.newUser = newUser;
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        firstNameLabel2 = new javax.swing.JLabel();
        lastNameLabel2 = new javax.swing.JLabel();
        ageLabel2 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        firstNameTextField2 = new javax.swing.JTextField();
        lastNameTextField1 = new javax.swing.JTextField();
        ageTextField1 = new javax.swing.JTextField();
        emailTextField1 = new javax.swing.JTextField();
        messageLabel1 = new javax.swing.JTextField();
        messageTextField1 = new javax.swing.JTextField();
        genderLabel1 = new javax.swing.JLabel();
        typeLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        genderField = new javax.swing.JLabel();
        patientTypeField = new javax.swing.JLabel();
        imageIcon = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        dateofbirthfield = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(204, 255, 255));
        titleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel2.setText("View Form");
        titleLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 0, 0), 1, true));

        firstNameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        firstNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firstNameLabel2.setText("First Name:");

        lastNameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lastNameLabel2.setText("Last Name:");

        ageLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ageLabel2.setText(" Age:");

        emailLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailLabel2.setText("Email:");

        firstNameTextField2.setEditable(false);
        firstNameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextField2ActionPerformed(evt);
            }
        });
        firstNameTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameTextField2KeyReleased(evt);
            }
        });

        lastNameTextField1.setEditable(false);
        lastNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextField1ActionPerformed(evt);
            }
        });
        lastNameTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameTextField1KeyReleased(evt);
            }
        });

        ageTextField1.setEditable(false);
        ageTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTextField1KeyReleased(evt);
            }
        });

        emailTextField1.setEditable(false);
        emailTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextField1KeyReleased(evt);
            }
        });

        messageLabel1.setEditable(false);
        messageLabel1.setBackground(new java.awt.Color(0, 0, 102));
        messageLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        messageLabel1.setText("Message:");
        messageLabel1.setBorder(null);

        messageTextField1.setEditable(false);
        messageTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        messageTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextField1ActionPerformed(evt);
            }
        });
        messageTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                messageTextField1KeyReleased(evt);
            }
        });

        genderLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        genderLabel1.setText("Gender:");

        typeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        typeLabel1.setText("Type:");

        genderField.setText("Gender");

        patientTypeField.setText("type");

        imageIcon.setText("Image");

        dateofbirth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateofbirth.setText("Date of birth:");

        dateofbirthfield.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ageLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(36, 36, 36))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dateofbirth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(dateofbirthfield, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genderLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(messageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(typeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lastNameLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(patientTypeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel2)
                            .addComponent(firstNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel2)
                            .addComponent(lastNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLabel2)
                            .addComponent(ageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateofbirth)
                            .addComponent(dateofbirthfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(genderField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(genderLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextField1KeyReleased

    private void messageTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextField1ActionPerformed

    private void emailTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextField1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_emailTextField1KeyReleased

    private void ageTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextField1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_ageTextField1KeyReleased

    private void lastNameTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTextField1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lastNameTextField1KeyReleased

    private void lastNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextField1ActionPerformed

    private void firstNameTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTextField2KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_firstNameTextField2KeyReleased

    private void firstNameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel2;
    private javax.swing.JTextField ageTextField1;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JLabel dateofbirthfield;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JTextField firstNameTextField2;
    private javax.swing.JLabel genderField;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JTextField lastNameTextField1;
    private javax.swing.JTextField messageLabel1;
    private javax.swing.JTextField messageTextField1;
    private javax.swing.JLabel patientTypeField;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel typeLabel1;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        firstNameTextField2.setText(this.newUser.getFirstname());
        lastNameTextField1.setText(this.newUser.getLastname());
        ageTextField1.setText(this.newUser.getAge());
        emailTextField1.setText(this.newUser.getEmail());
        messageTextField1.setText(this.newUser.getMessage());
        genderField.setText(this.newUser.getGender());
        patientTypeField.setText(this.newUser.getType());
        dateofbirthfield.setText(this.newUser.getDate());
        
        
        ImageIcon ii = new ImageIcon(this.newUser.getfilename());
//        Image image = ii.getImage().getScaledInstance(imageIcon.getWidth(), imageIcon.getHeight(), Image.SCALE_SMOOTH);
        imageIcon.setIcon(ii);
    }
}
